ALTER TABLE PHONGBAN
    ALTER COLUMN TenPhg NVARCHAR(30);

ALTER TABLE DEAN
    ALTER COLUMN DDiemDA NVARCHAR(20);

ALTER TABLE THANNHAN
    ALTER COLUMN TenTN NVARCHAR(20);

ALTER TABLE THANNHAN
    ALTER COLUMN Phai NVARCHAR(3);

ALTER TABLE THANNHAN
    ALTER COLUMN QuanHe NVARCHAR(15);